safe: true
title: "Introduction to Programming – UCSD CSE 8A"
source: .
destination: _site
lsi: false
url: "https://uscd-cse8a-w20.github.io/"
:pygments: true
navbar-links: 
  - [Do Now!](https://github.com/ucsd-cse8a-w21/ucsd-cse8a-w21.github.io/blob/main/index.md#do-now)
